// Exports every row of every portal.* table as a re-runnable INSERT script.
// Reads whichever database app/server/.env points at (read-only: SELECTs only).
//   node scripts/exportData.js ../database/fresh_install/03_data.sql
import 'dotenv/config'
import fs from 'fs'
import { getPool } from '../src/config/db.js'

const outFile = process.argv[2]
if (!outFile) {
  console.error('Usage: node scripts/exportData.js <output.sql>')
  process.exit(1)
}

const q = (s) => "N'" + String(s).replace(/'/g, "''") + "'"

function literal(value, type) {
  if (value === null || value === undefined) return 'NULL'
  if (value instanceof Date) {
    const iso = value.toISOString()
    return type === 'date' ? `'${iso.slice(0, 10)}'` : `'${iso.slice(0, 23).replace('Z', '')}'`
  }
  if (Buffer.isBuffer(value)) return '0x' + value.toString('hex')
  if (typeof value === 'boolean') return value ? '1' : '0'
  if (typeof value === 'number' || typeof value === 'bigint') return String(value)
  return q(value)
}

const pool = await getPool()
const tables = (
  await pool.request().query(`
    SELECT t.object_id, t.name,
           CASE WHEN EXISTS (SELECT 1 FROM sys.identity_columns i WHERE i.object_id = t.object_id) THEN 1 ELSE 0 END AS hasIdentity
    FROM sys.tables t WHERE t.schema_id = SCHEMA_ID('portal') ORDER BY t.name`)
).recordset

const fkPairs = (
  await pool.request().query(`
    SELECT OBJECT_NAME(parent_object_id) AS child, OBJECT_NAME(referenced_object_id) AS parent
    FROM sys.foreign_keys WHERE SCHEMA_NAME(schema_id) = 'portal' AND parent_object_id <> referenced_object_id`)
).recordset

// Parents before children.
const order = []
const pending = new Set(tables.map((t) => t.name))
while (pending.size) {
  const ready = [...pending].filter((n) => !fkPairs.some((p) => p.child === n && pending.has(p.parent)))
  if (!ready.length) throw new Error('Circular FK dependency among: ' + [...pending].join(', '))
  ready.sort().forEach((n) => { order.push(n); pending.delete(n) })
}

const lines = [
  '-- Syncaxis Company Portal — data export (generated by scripts/exportData.js).',
  '-- Run AFTER 02_schema_full.sql, against the empty SYNCAXIS_PORTAL database.',
  'USE SYNCAXIS_PORTAL;',
  'GO',
  'SET NOCOUNT ON;',
  'GO',
]
const summary = []

for (const name of order) {
  const t = tables.find((x) => x.name === name)
  const cols = (
    await pool.request().query(`
      SELECT c.name, ty.name AS type FROM sys.columns c JOIN sys.types ty ON ty.user_type_id = c.user_type_id
      WHERE c.object_id = ${t.object_id} AND c.is_computed = 0 AND ty.name NOT IN ('timestamp','rowversion')
      ORDER BY c.column_id`)
  ).recordset
  const rows = (await pool.request().query(`SELECT ${cols.map((c) => `[${c.name}]`).join(', ')} FROM portal.[${name}]`)).recordset
  summary.push(`${name}: ${rows.length}`)
  if (!rows.length) continue

  lines.push(`-- portal.${name} (${rows.length} rows)`)
  lines.push(`ALTER TABLE portal.[${name}] NOCHECK CONSTRAINT ALL;`)
  if (t.hasIdentity) lines.push(`SET IDENTITY_INSERT portal.[${name}] ON;`)
  const colList = cols.map((c) => `[${c.name}]`).join(', ')
  for (const r of rows) {
    lines.push(`INSERT INTO portal.[${name}] (${colList}) VALUES (${cols.map((c) => literal(r[c.name], c.type)).join(', ')});`)
  }
  if (t.hasIdentity) lines.push(`SET IDENTITY_INSERT portal.[${name}] OFF;`)
  lines.push(`ALTER TABLE portal.[${name}] WITH CHECK CHECK CONSTRAINT ALL;`, 'GO')
}
lines.push("PRINT 'Data load complete.';", 'GO')

fs.writeFileSync(outFile, lines.join('\n') + '\n')
console.log(summary.join('\n'))
process.exit(0)
